# Generated by Django 5.0.6 on 2024-05-21 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Content Name')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text'), ('embed', 'Embed')], max_length=255, verbose_name='Content Type')),
                ('url', models.URLField(blank=True, help_text='If the type is "embed", please provide the URL. Otherwise, leave this field blank.', null=True, verbose_name='Embed URL')),
                ('file', models.FileField(blank=True, help_text='If the type is "image" or "video", please upload the file.', null=True, upload_to='content/files/', verbose_name='Image/Video File')),
                ('text', models.TextField(blank=True, help_text='If the type is "text", please provide the text content.', null=True, verbose_name='Text Content')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Specify the duration of the content in seconds.', validators=[django.core.validators.MinValueValidator(3)], verbose_name='Duration (in seconds)')),
                ('is_active', models.BooleanField(default=True, help_text='Specify if the content is active or not.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'content',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contents', models.ManyToManyField(blank=True, related_name='playlists', to='signage.content')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'db_table': 'playlist',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlists', models.ManyToManyField(blank=True, related_name='screens', to='signage.playlist')),
            ],
            options={
                'verbose_name': 'Screen',
                'verbose_name_plural': 'Screens',
                'db_table': 'screen',
                'ordering': ['-id'],
            },
        ),
    ]
