# Generated by Django 5.0.6 on 2024-05-21 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.PositiveIntegerField(default=5, help_text='Specify the duration of the content in seconds.', validators=[django.core.validators.MinValueValidator(3)], verbose_name='Duration (in seconds)'),
        ),
    ]
