# Generated by Django 5.0.6 on 2024-05-30 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0003_content_ends_at_content_starts_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If the content is not active, it will not be displayed on the screens.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='content',
            name='starts_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 22, 26, 33, 940518, tzinfo=datetime.timezone.utc), help_text='Specify the start date and time for the content. If not specified, the content will be displayed immediately.', verbose_name='Starts At'),
            preserve_default=False,
        ),
    ]
