# Generated by Django 5.0.6 on 2024-05-30 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0004_alter_content_is_active_alter_content_starts_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Specify the duration of the content in seconds.', validators=[django.core.validators.MinValueValidator(3)], verbose_name='Duration (in seconds)'),
        ),
    ]
