# Generated by Django 5.0.6 on 2024-05-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0006_remove_playlist_contents_remove_screen_playlists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='slug',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If the playlist is not active, it will not be displayed on the screens.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the screen to provide more information.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If the screen is not active, it will not be displayed.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='name',
            field=models.CharField(help_text='Unique name for the screen to identify it.', max_length=255, unique=True, verbose_name='Screen Name'),
        ),
    ]
