# Generated by Django 5.0.6 on 2024-05-31 11:46

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0007_remove_screen_slug_alter_playlist_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(help_text='Unique name for the playlist to identify it.', max_length=255, unique=True, verbose_name='Playlist Name'),
        ),
        migrations.AddConstraint(
            model_name='screen',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_name_case_insensitive'),
        ),
    ]
