# Generated by Django 5.0.6 on 2024-08-08 13:52

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0008_alter_playlist_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='screen',
            name='unique_name_case_insensitive',
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique playlist name'),
        ),
        migrations.AddConstraint(
            model_name='screen',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique screen name'),
        ),
    ]
