# Generated by Django 5.0.6 on 2024-11-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0009_remove_screen_unique_name_case_insensitive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('embed', 'Embed')], max_length=255, verbose_name='Content Type'),
        ),
    ]
